version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS:Service
      Properties:
        TaskDefinitions: "arn:aws:ecs:us-east-2:111111:task-definition/DemoAppTaskDefinition:14"
        LoadBalancerInfo:
          ContainerName: "DemoAppContainer"
          ContainerPort: 8000